//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBuilder.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eng() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCBuilder.Localization.Eng", typeof(Eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty field.
        /// </summary>
        public static string Loc_Global_EmptyField {
            get {
                return ResourceManager.GetString("Loc_Global_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not right format!.
        /// </summary>
        public static string Loc_Global_NotRightFormat {
            get {
                return ResourceManager.GetString("Loc_Global_NotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Loc_Login_Button {
            get {
                return ResourceManager.GetString("Loc_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на email.
        /// </summary>
        public static string Loc_Login_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Loc_Login_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        public static string Loc_Login_Label {
            get {
                return ResourceManager.GetString("Loc_Login_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection failed.
        /// </summary>
        public static string Loc_Login_LoadError {
            get {
                return ResourceManager.GetString("Loc_Login_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password or email not correct.
        /// </summary>
        public static string Loc_Login_LoginError {
            get {
                return ResourceManager.GetString("Loc_Login_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на password.
        /// </summary>
        public static string Loc_Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Loc_Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Loc_Login_RegisterHypertext {
            get {
                return ResourceManager.GetString("Loc_Login_RegisterHypertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry.
        /// </summary>
        public static string Loc_Login_RetryButton {
            get {
                return ResourceManager.GetString("Loc_Login_RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string Loc_Reg_Address {
            get {
                return ResourceManager.GetString("Loc_Reg_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact number.
        /// </summary>
        public static string Loc_Reg_ContNum {
            get {
                return ResourceManager.GetString("Loc_Reg_ContNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Loc_Reg_Email {
            get {
                return ResourceManager.GetString("Loc_Reg_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This email alredy exist!.
        /// </summary>
        public static string Loc_Reg_Email_Err0 {
            get {
                return ResourceManager.GetString("Loc_Reg_Email_Err0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration error!.
        /// </summary>
        public static string Loc_Reg_Error {
            get {
                return ResourceManager.GetString("Loc_Reg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string Loc_Reg_FName {
            get {
                return ResourceManager.GetString("Loc_Reg_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Loc_Reg_Label {
            get {
                return ResourceManager.GetString("Loc_Reg_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string Loc_Reg_LName {
            get {
                return ResourceManager.GetString("Loc_Reg_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password dont equals!.
        /// </summary>
        public static string Loc_Reg_Pass_Err {
            get {
                return ResourceManager.GetString("Loc_Reg_Pass_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Loc_Reg_Password {
            get {
                return ResourceManager.GetString("Loc_Reg_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password.
        /// </summary>
        public static string Loc_Reg_RepeatPassword {
            get {
                return ResourceManager.GetString("Loc_Reg_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to login.
        /// </summary>
        public static string Loc_Reg_RetToLogin {
            get {
                return ResourceManager.GetString("Loc_Reg_RetToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        public static string Loc_Reg_Submit {
            get {
                return ResourceManager.GetString("Loc_Reg_Submit", resourceCulture);
            }
        }
    }
}
