//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBuilder.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eng() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCBuilder.Localization.Eng", typeof(Eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string Loc_Basket_Note {
            get {
                return ResourceManager.GetString("Loc_Basket_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shoping cart.
        /// </summary>
        public static string Loc_Basket_Tittle {
            get {
                return ResourceManager.GetString("Loc_Basket_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop filters.
        /// </summary>
        public static string Loc_Catalog_FDrop {
            get {
                return ResourceManager.GetString("Loc_Catalog_FDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set filters.
        /// </summary>
        public static string Loc_Catalog_FSet {
            get {
                return ResourceManager.GetString("Loc_Catalog_FSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product name.
        /// </summary>
        public static string Loc_Catalog_Search {
            get {
                return ResourceManager.GetString("Loc_Catalog_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog.
        /// </summary>
        public static string Loc_Catalog_Tittle {
            get {
                return ResourceManager.GetString("Loc_Catalog_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string Loc_FilterPopup_From {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string Loc_FilterPopup_Price {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        public static string Loc_FilterPopup_Tittle {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To.
        /// </summary>
        public static string Loc_FilterPopup_To {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Loc_FilterPopup_Type {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string Loc_Global_Confirm {
            get {
                return ResourceManager.GetString("Loc_Global_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty field.
        /// </summary>
        public static string Loc_Global_EmptyField {
            get {
                return ResourceManager.GetString("Loc_Global_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not right format!.
        /// </summary>
        public static string Loc_Global_NotRightFormat {
            get {
                return ResourceManager.GetString("Loc_Global_NotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Loc_Login_Button {
            get {
                return ResourceManager.GetString("Loc_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на email.
        /// </summary>
        public static string Loc_Login_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Loc_Login_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        public static string Loc_Login_Label {
            get {
                return ResourceManager.GetString("Loc_Login_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection failed.
        /// </summary>
        public static string Loc_Login_LoadError {
            get {
                return ResourceManager.GetString("Loc_Login_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password or email not correct.
        /// </summary>
        public static string Loc_Login_LoginError {
            get {
                return ResourceManager.GetString("Loc_Login_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на password.
        /// </summary>
        public static string Loc_Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Loc_Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Loc_Login_RegisterHypertext {
            get {
                return ResourceManager.GetString("Loc_Login_RegisterHypertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry.
        /// </summary>
        public static string Loc_Login_RetryButton {
            get {
                return ResourceManager.GetString("Loc_Login_RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Template deleted!.
        /// </summary>
        public static string Loc_MesPopup_DelTemplate {
            get {
                return ResourceManager.GetString("Loc_MesPopup_DelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Loc_MP_Submit {
            get {
                return ResourceManager.GetString("Loc_MP_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Loc_Options_Lang {
            get {
                return ResourceManager.GetString("Loc_Options_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string Loc_Options_Title {
            get {
                return ResourceManager.GetString("Loc_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failure.
        /// </summary>
        public static string Loc_Popup_Global_Failure {
            get {
                return ResourceManager.GetString("Loc_Popup_Global_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string Loc_Popup_Global_Success {
            get {
                return ResourceManager.GetString("Loc_Popup_Global_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This product added to basket!.
        /// </summary>
        public static string Loc_Popup_ProdCart_Added {
            get {
                return ResourceManager.GetString("Loc_Popup_ProdCart_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To basket.
        /// </summary>
        public static string Loc_ProdCart_ToBasket {
            get {
                return ResourceManager.GetString("Loc_ProdCart_ToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string Loc_Reg_Address {
            get {
                return ResourceManager.GetString("Loc_Reg_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact number.
        /// </summary>
        public static string Loc_Reg_ContNum {
            get {
                return ResourceManager.GetString("Loc_Reg_ContNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Loc_Reg_Email {
            get {
                return ResourceManager.GetString("Loc_Reg_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This email alredy exist!.
        /// </summary>
        public static string Loc_Reg_Email_Err0 {
            get {
                return ResourceManager.GetString("Loc_Reg_Email_Err0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration error!.
        /// </summary>
        public static string Loc_Reg_Error {
            get {
                return ResourceManager.GetString("Loc_Reg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string Loc_Reg_FName {
            get {
                return ResourceManager.GetString("Loc_Reg_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Loc_Reg_Label {
            get {
                return ResourceManager.GetString("Loc_Reg_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string Loc_Reg_LName {
            get {
                return ResourceManager.GetString("Loc_Reg_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password dont equals!.
        /// </summary>
        public static string Loc_Reg_Pass_Err {
            get {
                return ResourceManager.GetString("Loc_Reg_Pass_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Loc_Reg_Password {
            get {
                return ResourceManager.GetString("Loc_Reg_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You successful registred.
        /// </summary>
        public static string Loc_Reg_Popup_Message {
            get {
                return ResourceManager.GetString("Loc_Reg_Popup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string Loc_Reg_Popup_Title {
            get {
                return ResourceManager.GetString("Loc_Reg_Popup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password.
        /// </summary>
        public static string Loc_Reg_RepeatPassword {
            get {
                return ResourceManager.GetString("Loc_Reg_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to login.
        /// </summary>
        public static string Loc_Reg_RetToLogin {
            get {
                return ResourceManager.GetString("Loc_Reg_RetToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        public static string Loc_Reg_Submit {
            get {
                return ResourceManager.GetString("Loc_Reg_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Loc_TEdit_Description {
            get {
                return ResourceManager.GetString("Loc_TEdit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Loc_TEdit_Name {
            get {
                return ResourceManager.GetString("Loc_TEdit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Template editor.
        /// </summary>
        public static string Loc_TEdit_Tittle {
            get {
                return ResourceManager.GetString("Loc_TEdit_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Have empty slots!.
        /// </summary>
        public static string Loc_TempEdit_Popup_HaveES {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_HaveES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name field is empty!.
        /// </summary>
        public static string Loc_TempEdit_Popup_NameError {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Validation error.
        /// </summary>
        public static string Loc_TempEdit_Popup_Tittle {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incompatible components!.
        /// </summary>
        public static string Loc_TempEdit_Popup_VadlidError {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_VadlidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty.
        /// </summary>
        public static string Loc_TempEdit_ProdNameUnset {
            get {
                return ResourceManager.GetString("Loc_TempEdit_ProdNameUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slot is empty!.
        /// </summary>
        public static string Loc_TempEdit_SlotIsEmpty {
            get {
                return ResourceManager.GetString("Loc_TempEdit_SlotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not equals.
        /// </summary>
        public static string Loc_TempEdit_ValidateErrMesTemp {
            get {
                return ResourceManager.GetString("Loc_TempEdit_ValidateErrMesTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string Loc_TView_All {
            get {
                return ResourceManager.GetString("Loc_TView_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string Loc_TView_Create {
            get {
                return ResourceManager.GetString("Loc_TView_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My.
        /// </summary>
        public static string Loc_TView_My {
            get {
                return ResourceManager.GetString("Loc_TView_My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Template name.
        /// </summary>
        public static string Loc_TView_Search {
            get {
                return ResourceManager.GetString("Loc_TView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates.
        /// </summary>
        public static string Loc_TView_Tittle {
            get {
                return ResourceManager.GetString("Loc_TView_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string Loc_User_Address {
            get {
                return ResourceManager.GetString("Loc_User_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Loc_User_Email {
            get {
                return ResourceManager.GetString("Loc_User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Loc_User_Name {
            get {
                return ResourceManager.GetString("Loc_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number.
        /// </summary>
        public static string Loc_User_Number {
            get {
                return ResourceManager.GetString("Loc_User_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items count.
        /// </summary>
        public static string Loc_User_OH_ItemsCount {
            get {
                return ResourceManager.GetString("Loc_User_OH_ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string Loc_User_OH_Status {
            get {
                return ResourceManager.GetString("Loc_User_OH_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total price.
        /// </summary>
        public static string Loc_User_OH_TotalPrice {
            get {
                return ResourceManager.GetString("Loc_User_OH_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order history.
        /// </summary>
        public static string Loc_User_OrderHistory {
            get {
                return ResourceManager.GetString("Loc_User_OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string Loc_User_Tittle {
            get {
                return ResourceManager.GetString("Loc_User_Tittle", resourceCulture);
            }
        }
    }
}
