//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBuilder.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rus() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCBuilder.Localization.Rus", typeof(Rus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заметка.
        /// </summary>
        public static string Loc_Basket_Note {
            get {
                return ResourceManager.GetString("Loc_Basket_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корзина.
        /// </summary>
        public static string Loc_Basket_Tittle {
            get {
                return ResourceManager.GetString("Loc_Basket_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        public static string Loc_Catalog_FDrop {
            get {
                return ResourceManager.GetString("Loc_Catalog_FDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтры.
        /// </summary>
        public static string Loc_Catalog_FSet {
            get {
                return ResourceManager.GetString("Loc_Catalog_FSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название продукта.
        /// </summary>
        public static string Loc_Catalog_Search {
            get {
                return ResourceManager.GetString("Loc_Catalog_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог.
        /// </summary>
        public static string Loc_Catalog_Tittle {
            get {
                return ResourceManager.GetString("Loc_Catalog_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От.
        /// </summary>
        public static string Loc_FilterPopup_From {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Loc_FilterPopup_Price {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтры.
        /// </summary>
        public static string Loc_FilterPopup_Tittle {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До.
        /// </summary>
        public static string Loc_FilterPopup_To {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string Loc_FilterPopup_Type {
            get {
                return ResourceManager.GetString("Loc_FilterPopup_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string Loc_Global_Confirm {
            get {
                return ResourceManager.GetString("Loc_Global_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустое поле.
        /// </summary>
        public static string Loc_Global_EmptyField {
            get {
                return ResourceManager.GetString("Loc_Global_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не правильный формат!.
        /// </summary>
        public static string Loc_Global_NotRightFormat {
            get {
                return ResourceManager.GetString("Loc_Global_NotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Loc_Login_Button {
            get {
                return ResourceManager.GetString("Loc_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на почта.
        /// </summary>
        public static string Loc_Login_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Loc_Login_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Loc_Login_Label {
            get {
                return ResourceManager.GetString("Loc_Login_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка соеденения.
        /// </summary>
        public static string Loc_Login_LoadError {
            get {
                return ResourceManager.GetString("Loc_Login_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль или почта не верны.
        /// </summary>
        public static string Loc_Login_LoginError {
            get {
                return ResourceManager.GetString("Loc_Login_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пароль.
        /// </summary>
        public static string Loc_Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Loc_Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Loc_Login_RegisterHypertext {
            get {
                return ResourceManager.GetString("Loc_Login_RegisterHypertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повтор.
        /// </summary>
        public static string Loc_Login_RetryButton {
            get {
                return ResourceManager.GetString("Loc_Login_RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сборка удалена!.
        /// </summary>
        public static string Loc_MesPopup_DelTemplate {
            get {
                return ResourceManager.GetString("Loc_MesPopup_DelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо.
        /// </summary>
        public static string Loc_MP_Submit {
            get {
                return ResourceManager.GetString("Loc_MP_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Loc_Options_Lang {
            get {
                return ResourceManager.GetString("Loc_Options_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Loc_Options_Title {
            get {
                return ResourceManager.GetString("Loc_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Loc_Popup_Global_Failure {
            get {
                return ResourceManager.GetString("Loc_Popup_Global_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string Loc_Popup_Global_Success {
            get {
                return ResourceManager.GetString("Loc_Popup_Global_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт добавлен в корзину.
        /// </summary>
        public static string Loc_Popup_ProdCart_Added {
            get {
                return ResourceManager.GetString("Loc_Popup_ProdCart_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В корзину.
        /// </summary>
        public static string Loc_ProdCart_ToBasket {
            get {
                return ResourceManager.GetString("Loc_ProdCart_ToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string Loc_Reg_Address {
            get {
                return ResourceManager.GetString("Loc_Reg_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактный телефон.
        /// </summary>
        public static string Loc_Reg_ContNum {
            get {
                return ResourceManager.GetString("Loc_Reg_ContNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта.
        /// </summary>
        public static string Loc_Reg_Email {
            get {
                return ResourceManager.GetString("Loc_Reg_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это почта уже используется!.
        /// </summary>
        public static string Loc_Reg_Email_Err0 {
            get {
                return ResourceManager.GetString("Loc_Reg_Email_Err0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка регистрации!.
        /// </summary>
        public static string Loc_Reg_Error {
            get {
                return ResourceManager.GetString("Loc_Reg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Loc_Reg_FName {
            get {
                return ResourceManager.GetString("Loc_Reg_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Loc_Reg_Label {
            get {
                return ResourceManager.GetString("Loc_Reg_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string Loc_Reg_LName {
            get {
                return ResourceManager.GetString("Loc_Reg_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не равный!.
        /// </summary>
        public static string Loc_Reg_Pass_Err {
            get {
                return ResourceManager.GetString("Loc_Reg_Pass_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Loc_Reg_Password {
            get {
                return ResourceManager.GetString("Loc_Reg_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы успешно зарегестрированы.
        /// </summary>
        public static string Loc_Reg_Popup_Message {
            get {
                return ResourceManager.GetString("Loc_Reg_Popup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string Loc_Reg_Popup_Title {
            get {
                return ResourceManager.GetString("Loc_Reg_Popup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторить пароль.
        /// </summary>
        public static string Loc_Reg_RepeatPassword {
            get {
                return ResourceManager.GetString("Loc_Reg_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к входу.
        /// </summary>
        public static string Loc_Reg_RetToLogin {
            get {
                return ResourceManager.GetString("Loc_Reg_RetToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string Loc_Reg_Submit {
            get {
                return ResourceManager.GetString("Loc_Reg_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Loc_TEdit_Description {
            get {
                return ResourceManager.GetString("Loc_TEdit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Loc_TEdit_Name {
            get {
                return ResourceManager.GetString("Loc_TEdit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор сборок.
        /// </summary>
        public static string Loc_TEdit_Tittle {
            get {
                return ResourceManager.GetString("Loc_TEdit_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есть пустые слоты!.
        /// </summary>
        public static string Loc_TempEdit_Popup_HaveES {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_HaveES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле имени пустое!.
        /// </summary>
        public static string Loc_TempEdit_Popup_NameError {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проверки.
        /// </summary>
        public static string Loc_TempEdit_Popup_Tittle {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не подходящие компоненты!.
        /// </summary>
        public static string Loc_TempEdit_Popup_VadlidError {
            get {
                return ResourceManager.GetString("Loc_TempEdit_Popup_VadlidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пусто.
        /// </summary>
        public static string Loc_TempEdit_ProdNameUnset {
            get {
                return ResourceManager.GetString("Loc_TempEdit_ProdNameUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустой слот!.
        /// </summary>
        public static string Loc_TempEdit_SlotIsEmpty {
            get {
                return ResourceManager.GetString("Loc_TempEdit_SlotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не совподение.
        /// </summary>
        public static string Loc_TempEdit_ValidateErrMesTemp {
            get {
                return ResourceManager.GetString("Loc_TempEdit_ValidateErrMesTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string Loc_TView_All {
            get {
                return ResourceManager.GetString("Loc_TView_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        public static string Loc_TView_Create {
            get {
                return ResourceManager.GetString("Loc_TView_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои.
        /// </summary>
        public static string Loc_TView_My {
            get {
                return ResourceManager.GetString("Loc_TView_My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название сборки.
        /// </summary>
        public static string Loc_TView_Search {
            get {
                return ResourceManager.GetString("Loc_TView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сборки.
        /// </summary>
        public static string Loc_TView_Tittle {
            get {
                return ResourceManager.GetString("Loc_TView_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string Loc_User_Address {
            get {
                return ResourceManager.GetString("Loc_User_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электорнная почта.
        /// </summary>
        public static string Loc_User_Email {
            get {
                return ResourceManager.GetString("Loc_User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Loc_User_Name {
            get {
                return ResourceManager.GetString("Loc_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактный номер.
        /// </summary>
        public static string Loc_User_Number {
            get {
                return ResourceManager.GetString("Loc_User_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во пунктов.
        /// </summary>
        public static string Loc_User_OH_ItemsCount {
            get {
                return ResourceManager.GetString("Loc_User_OH_ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Loc_User_OH_Status {
            get {
                return ResourceManager.GetString("Loc_User_OH_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Loc_User_OH_TotalPrice {
            get {
                return ResourceManager.GetString("Loc_User_OH_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История заказов.
        /// </summary>
        public static string Loc_User_OrderHistory {
            get {
                return ResourceManager.GetString("Loc_User_OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string Loc_User_Tittle {
            get {
                return ResourceManager.GetString("Loc_User_Tittle", resourceCulture);
            }
        }
    }
}
